/* user table */
CREATE TABLE IF NOT EXISTS user (
  user_id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  firstName VARCHAR(60),
  mail VARCHAR(100) NOT NULL,
  password VARCHAR(20) NOT NULL
);
